version: "3.9"

services:
  powerplant-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_KEY=your-secret-key
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet localhost:3000/api/v1/power-plants || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

# Add services like db, cache, etc. as needed
